# [INICIO cloudbuild_node]
steps:
# Intalación de dependencias
- name: 'gcr.io/cloud-builders/docker:19.03.8'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/reto-devops-clm:v$BUILD_ID']
# Ejecutamos pruebas
- name: 'gcr.io/cloud-builders/docker:19.03.8'
  args: ['push',  'gcr.io/$PROJECT_ID/reto-devops-clm:v$BUILD_ID']
  env:
    - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
    - CLOUDSDK_CONTAINER_CLOUSTER=${_CLOUDSDK_CONTAINER_CLOUSTER}
# [FIN cloudbuild_node]