# [INICIO cloudbuild_node]
steps:
# Intalación de dependencias
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PRJECT_ID/reto-devops-clm:v$BUILD_ID']
# Ejecutamos pruebas
- name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'gcr.io/$PRJECT_ID/reto-devops-clm:v$BUILD_ID']
  env:
    - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
    - CLOUDSDK_CONTAINER_CLOUSTER=${_CLOUDSDK_CONTAINER_CLOUSTER}
# Ejecutamos aplicacion
- name: node
  entrypoint: npm
  args: ['start']
# [FIN cloudbuild_node]